### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fregante**

### CODE REVIEW

**Comment by fregante** [comment]
This still has a lot of bugs. Not worth putting time into

**Comment by oroce** [comment]
:(

**Comment by fregante** [comment]
Tell me about it, :/ I think the bugs were mostly of jade-php.  I hoped to use it but being mostly-unsupported I can't risk running into more issues as my current project grows.

**Comment by oroce** [comment]
Please do.
What was the problem? I really would like to help. What issues are you running into?

**Comment by fregante** [comment]
gulp-jade-php uses an old version of jade-php that doesn't support PHP code in attributes, so in this:

``` js
a(href=fn('about'))
```

`fn()` would be called during compilation, in JS. The latest version of jade-php support attributes in PHP but it's not compatible with gulp-jade-php (or maybe it's just buggy)

Also, even if that was supported, this wouldn't be:

``` js
a(href=URL::to_assets('about'))
```

… because that double colon is not supported.

**Comment by oroce** [comment]
Okay that's a great start, could you add some tests for these? I would do some debugging if we would have some failing tests to identify the problem.

Thanks

**Comment by fregante** [comment]
No, I don't have a whole lot of time and can't maintain this project

**Comment by oroce** [comment]
I wasnt asking for maintaining the project. I just need some tests to debug the problem. I would do the debugging and identifying the problems. And I would still maintain the module.

**Comment by fregante** [comment]
If you want to maintain it then make sure that all the dependencies are up to date and working. The bug related to `URL::to_asset` should then be filed in `jade-php`

**Comment by fregante** [comment]
I'd suggest looking into https://github.com/SE7ENSKY/jade2php/

It's slightly newer, more tested and it seems to work nicely. It also works around the `FOO::bar()` issue nicely by using https://github.com/sstur/js2php and converting `FOO.bar()` into that during compilation, so no changes to the Jade parser are necessary and existing Jade files might just work.

**Pull request closed without merging**
